### PR TITLE
ITS-3295 Feature toggle for FMN field level encryption

### PR DESCRIPTION
**Pull request by rambabu-posa**

### CODE REVIEW

**Review by ajchilts — CHANGES_REQUESTED** [review]
I think this can be achieved in a much simpler way. 

See this implementation:

Conf:
https://github.com/hmrc/amls-frontend/blob/main/conf/application.conf#L90

https://github.com/hmrc/amls-frontend/blob/7346060db8937147fb42a901a4ec470519638f54/app/config/ApplicationConfig.scala#L92

Usage (simple):

Example writes: https://github.com/hmrc/amls-frontend/blob/7346060db8937147fb42a901a4ec470519638f54/app/services/cache/MongoCacheClient.scala#L116-L120

Example Upsert: https://github.com/hmrc/amls-frontend/blob/7346060db8937147fb42a901a4ec470519638f54/app/services/cache/MongoCacheClient.scala#L161-L165

Example create or update:  https://github.com/hmrc/amls-frontend/blob/7346060db8937147fb42a901a4ec470519638f54/app/services/cache/MongoCacheClient.scala#L116-L119

Example find: https://github.com/hmrc/amls-frontend/blob/7346060db8937147fb42a901a4ec470519638f54/app/services/cache/MongoCacheClient.scala#L116-L179

So its literally just a switch.

**Comment by ajchilts** [comment]
@rambabu-posa  - Another way to achieve this is to keep your 'EncryptedPersonalDetailsValidationRepository' and switch out the modules that get loaded based on config. 

Let me see if I can dig out an example of that also.

**Comment by rambabu-posa** [comment]
@ajchilts  amls-frontend implementation is different to our SMN/FMN implementation.

**Comment by ajchilts** [comment]
Alternative Example:

Config : https://github.com/hmrc/ctc-guarantee-balance-frontend/blob/main/conf/application.conf#L32C1-L33

In this case a V1 Module : https://github.com/hmrc/ctc-guarantee-balance-frontend/blob/main/app/config/V1Module.scala

and V2 Module: https://github.com/hmrc/ctc-guarantee-balance-frontend/blob/main/app/config/V2Module.scala

**Pull request closed without merging**
